`Linear Algebra library in Python

Building block for Pandas

Dealing with Vectors (1-d) and Matricies (2-d or more) arrays

## Part 1: NumPy Arrays

Arrays from lists

In [3]:
import numpy as np

In [6]:
list_1d = [5,3,8]

In [5]:
np.array(list_1d)

array([5, 3, 8])

In [7]:
list_2d = [[3,7,10],[4,2,5]]

In [8]:
list_2d

[[3, 7, 10], [4, 2, 5]]

In [9]:
np.array(list_2d)

array([[ 3,  7, 10],
       [ 4,  2,  5]])

Arrays from ranges(np.arrange)

In [10]:
np.arange(3,10)

array([3, 4, 5, 6, 7, 8, 9])

Arrays from ranges(np.arange)

In [13]:
np.arange(2,10,2)

array([2, 4, 6, 8])

Arrays from ranges(np.linspace)

In [16]:
np.linspace(1,20,10)

array([ 1.        ,  3.11111111,  5.22222222,  7.33333333,  9.44444444,
       11.55555556, 13.66666667, 15.77777778, 17.88888889, 20.        ])

In [17]:
np.linspace((1,1), (10,5), 10)

array([[ 1.        ,  1.        ],
       [ 2.        ,  1.44444444],
       [ 3.        ,  1.88888889],
       [ 4.        ,  2.33333333],
       [ 5.        ,  2.77777778],
       [ 6.        ,  3.22222222],
       [ 7.        ,  3.66666667],
       [ 8.        ,  4.11111111],
       [ 9.        ,  4.55555556],
       [10.        ,  5.        ]])

Arrays with random values

In [18]:
np.random.rand(4)

array([0.70507517, 0.87441136, 0.99150594, 0.72260707])

In [19]:
np.random.rand(3,4)

array([[0.34963766, 0.70716989, 0.60307676, 0.61095131],
       [0.19990065, 0.505048  , 0.58381965, 0.85131542],
       [0.7767489 , 0.88342331, 0.31472885, 0.32971937]])

Stadnard distribution from 1 to -1

In [20]:
np.random.randn(5)

array([ 0.20584379, -0.63387276,  0.0899255 ,  1.40460076,  1.13435413])

In [21]:
np.random.randn(6,4)

array([[-1.11062311, -0.10837786, -0.65122088, -0.88847211],
       [ 0.28147942,  1.59017894,  0.86241207, -1.57746927],
       [ 0.07668552, -0.66765988, -0.41164879, -0.22649407],
       [-1.63590425, -0.45807419,  0.07185824, -0.81448983],
       [-0.91896112,  0.42783295, -0.34192732,  0.62808979],
       [ 1.27185461, -0.38134674,  0.46794348,  0.26697678]])

Standarad Arrays(zeros, ones, identity matrix)

In [23]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [25]:
np.ones(4)

array([1., 1., 1., 1.])

In [26]:
np.ones((4,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

Identity Matrix

In [27]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

Reshape Arrays

In [28]:
arr = np.random.rand(12)

In [29]:
arr

array([0.82986388, 0.96357072, 0.71117248, 0.55913717, 0.60434993,
       0.14310881, 0.06465578, 0.43548532, 0.92196602, 0.60102893,
       0.94616187, 0.57344561])

In [30]:
arr.shape

(12,)

In [31]:
arr.reshape(3,4)

array([[0.82986388, 0.96357072, 0.71117248, 0.55913717],
       [0.60434993, 0.14310881, 0.06465578, 0.43548532],
       [0.92196602, 0.60102893, 0.94616187, 0.57344561]])

In [32]:
arr.reshape(2, 6)

array([[0.82986388, 0.96357072, 0.71117248, 0.55913717, 0.60434993,
        0.14310881],
       [0.06465578, 0.43548532, 0.92196602, 0.60102893, 0.94616187,
        0.57344561]])