In [ ]:
#import statements

In [4]:
import numpy as np

In [5]:
# 1-a) Create an 1-d array named 'arr_int' of integers from 45 to 55 inclusive
# 1-b) Read back first 4 elements of 'arr_int'
# 1-c) Read back last element of 'arr_int'

In [6]:
arr_int = np.arange(45, 56)

In [8]:
arr_int[:4]

array([45, 46, 47, 48])

In [9]:
arr_int[-1]

55

In [ ]:
# 2-a) Create a 1-d array named 'arr_1' of 12 values from the random-normal distribution
# 2-b) Create a boolean array named ' arr_1_bool' which has "True" where the value in 'arr_1' is greater than 0.5
# 2-c) Reshape the 1-d array 'arr_1' to a 3 row, 4 column 2-d array called 'arr_2'

In [10]:
arr_1 = np.random.randn(12)

In [14]:
arr_1

array([-1.16012781, -0.78005182,  0.16882466, -0.13197441, -1.96774912,
       -0.85934797, -0.29688215,  0.6290534 , -1.73087968, -1.23375691,
       -0.36635824,  1.22377155])

In [12]:
arr_1_bool = arr_1 > 0.5

In [15]:
arr_1_bool

array([False, False, False, False, False, False, False,  True, False,
       False, False,  True])

In [16]:
arr_2 = arr_1.reshape(3,4)

In [18]:
arr_2 

array([[-1.16012781, -0.78005182,  0.16882466, -0.13197441],
       [-1.96774912, -0.85934797, -0.29688215,  0.6290534 ],
       [-1.73087968, -1.23375691, -0.36635824,  1.22377155]])

In [ ]:
# 3-a) Add first 4 elements of 'arr_int' to first row of 'arr_2'. Store the result as 'arr_3'
# 3-b) Find the mean of 'arr_3'

In [19]:
arr_3 = arr_1[:4] + arr_2[0]

In [20]:
arr_3 

array([-2.32025562, -1.56010363,  0.33764931, -0.26394882])

In [21]:
arr_3.mean()

-0.9516646889532767