#### Reading from 1-d arrays using index

In [20]:
import numpy as np

In [12]:
arr1 = np.arange(3, 9)

In [13]:
arr1

array([3, 4, 5, 6, 7, 8])

In [14]:
arr1[5]

8

In [15]:
arr1[:5]

array([3, 4, 5, 6, 7])

In [16]:
arr1[2:]

array([5, 6, 7, 8])

In [18]:
arr1[-1] 

8

#### Slice vs Copy

In [21]:
sl_arr1 = arr1[1:3]

In [22]:
sl_arr1

array([4, 5])

In [23]:
sl_arr1[:] = 25

In [24]:
sl_arr1

array([25, 25])

In [25]:
arr1

array([ 3, 25, 25,  6,  7,  8])

In [27]:
cp_arr1 = arr1.copy()

In [28]:
cp_arr1

array([ 3, 25, 25,  6,  7,  8])

In [32]:
cp_arr1[1] = 111

In [33]:
arr1 

array([ 3, 25, 25,  6,  7,  8])

In [34]:
cp_arr1

array([  3, 111,  25,   6,   7,   8])

#### Reading from 2-d arrays using index

In [37]:
np_2d_arr=np.array([[2,3,4],[5,7,9],[11,22,33]])

In [38]:
np_2d_arr

array([[ 2,  3,  4],
       [ 5,  7,  9],
       [11, 22, 33]])

In [39]:
np_2d_arr[0]

array([2, 3, 4])

In [40]:
np_2d_arr[1][2]

9

In [41]:
np_2d_arr[1,2]

9

In [42]:
np_2d_arr[:,2]

array([ 4,  9, 33])

In [43]:
np_2d_arr[:2,:2]

array([[2, 3],
       [5, 7]])

#### Reading from 1-d arrays using conditionals

In [46]:
rand1_arr=np.random.randn(10)

In [47]:
rand1_arr

array([-0.38682846,  0.37808543,  2.20985415,  0.03154075,  2.2629176 ,
        0.03945605, -1.57472728,  0.22083632, -0.25489851,  0.44372705])

In [48]:
bool_arr = rand1_arr > 0

In [49]:
bool_arr

array([False,  True,  True,  True,  True,  True, False,  True, False,
        True])

In [51]:
rand1_arr[bool_arr]

array([0.37808543, 2.20985415, 0.03154075, 2.2629176 , 0.03945605,
       0.22083632, 0.44372705])

In [53]:
rand1_arr[rand1_arr > 0]

array([0.37808543, 2.20985415, 0.03154075, 2.2629176 , 0.03945605,
       0.22083632, 0.44372705])

#### Reading from 2-d using conditionals

In [71]:
rand_2d_arr = np.random.randn(15).reshape(3,5)

In [72]:
rand_2d_arr

array([[ 1.46690843,  1.83797483,  1.20426318, -1.46571623, -1.30011224],
       [-1.44958385,  0.05960466,  0.71556778,  0.03699715,  0.78898245],
       [-0.89891717,  0.67741748,  0.3868817 ,  0.56380408,  0.40852487]])

In [73]:
bool_2d_arr = rand_2d_arr > 0

In [74]:
bool_2d_arr

array([[ True,  True,  True, False, False],
       [False,  True,  True,  True,  True],
       [False,  True,  True,  True,  True]])

In [75]:
rand_2d_arr[bool_2d_arr]

array([1.46690843, 1.83797483, 1.20426318, 0.05960466, 0.71556778,
       0.03699715, 0.78898245, 0.67741748, 0.3868817 , 0.56380408,
       0.40852487])

In [76]:
bool_2d_arr[:,1]

array([ True,  True,  True])

In [77]:
rand_2d_arr[bool_2d_arr]

array([1.46690843, 1.83797483, 1.20426318, 0.05960466, 0.71556778,
       0.03699715, 0.78898245, 0.67741748, 0.3868817 , 0.56380408,
       0.40852487])

In [78]:
bool_2d_arr[1,:]

array([False,  True,  True,  True,  True])

In [79]:
rand_2d_arr[:,bool_2d_arr[1,:]]

array([[ 1.83797483,  1.20426318, -1.46571623, -1.30011224],
       [ 0.05960466,  0.71556778,  0.03699715,  0.78898245],
       [ 0.67741748,  0.3868817 ,  0.56380408,  0.40852487]])